theme: jekyll-theme-minimal

title: Kshitij Mohan's Journal
tagline: "Data Scientist | Generative AI Architect | NLP Specialist | LLM Innovator"
description: "Advancing Generative AI, NLP, and Large Language Models for scalable, data-driven solutions."
author: Kshitij Mohan

email: kshitijmhn@gmail.com
phone: +91-991-029-5298

kaggle: https://kaggle.com/kshitijmohan
linkedinurl: https://www.linkedin.com/in/kshitij-mhn
githurl: https://github.com/Kshitij-M
twitterurl: ""
stackoverflowurl: ""

repository: Kshitij-M/Kshitij-M.github.io
google_analytics: UA-144488030-1

plugins:
  - jekyll-seo-tag